//
//  YSVideoPlayerStyleKit.h
//  YSVideoPlayer
//
//  Created by Yu Sugawara on 2016/04/09.
//  Copyright (c) 2016 Picos LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface YSVideoPlayerStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* playTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* pauseTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* replayTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* sliderThumbTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* reloadTargets;

// Generated Images
+ (UIImage*)imageOfPlay;
+ (UIImage*)imageOfPause;
+ (UIImage*)imageOfReplay;
+ (UIImage*)imageOfSliderThumb;
+ (UIImage*)imageOfReload;

@end
